# Prospero
#
# You should have received a copy of the license along with this program.
#
# Licensed under
# - GNU Affero General Public License V3
# - CeCILL Affero compliant

# GitLab CI/CD Pipeline Configuration file.
#
# See https://docs.gitlab.com/ee/ci/yaml/

image: ruby:2.6.5-alpine

stages:
  - checkstyle
  - test
  - deploy

checkstyle:
  stage: checkstyle
  before_script:
    # Install system requirements
    - apk add g++ make
    # Install Rubocop
    - gem install rubocop -v '~> 0.77.0'
  script:
    - rubocop

test:
  stage: test
  services:
    - postgres:10
  variables:
    COVERAGE: enabled
    DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: enabled
    DATABASE_URL: postgres://prospero:prospero@postgres:5432/prospero_test
    POSTGRES_USER: prospero
    POSTGRES_PASSWORD: prospero
    RAILS_ENV: test
  before_script:
    # Install system requirements
    - apk add g++ make postgresql-dev yarn nodejs
    # Install Bundler 2
    - gem install bundler:2.0.2
    # Build app
    - bundle install --with test
    - yarn install
    # Create database
    - rake db:create db:migrate
  script:
    - bundle exec rspec
  coverage: /\(\d+.\d+\%\) covered/
  artifacts:
    paths:
      - coverage

# Publish coverage report
pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - develop

# If 'develop' has just been merged into to 'master', then create a Merge Request
# of 'master' into 'hotfix'.
#
# If 'hotfix' has just been merged into 'master', then create a Merge Request
# of 'master' into 'develop'.
#
# see docs/versioning_policy.md
synchronize-main-branches:
  stage: deploy
  before_script:
    - apk add bash curl jq
    - merged_branch=$(tools/ci_cd/print-merge-source.sh $CI_COMMIT_TITLE)
    - if [ "$merged_branch" == "develop" ]; then target=hotfix; else target=develop; fi
  script: >
    tools/ci_cd/create-merge-request.sh \
      --gitlab-url $GITLAB_URL \
      --access-token $ACCESS_TOKEN \
      --project-name $CI_PROJECT_NAME \
      --project-namespace $CI_PROJECT_NAMESPACE \
      --source-branch master \
      --target-branch $target \
      --assignee-id $AUTOMATE_MERGE_ASSIGNEE_ID
  only:
    refs:
      - master
    variables:
      - $GITLAB_URL
      - $ACCESS_TOKEN
      - $AUTOMATE_MERGE_ASSIGNEE_ID
