AllCops:
  Exclude:
    - bin/**/*
    - config.ru
    - db/schema.rb
    - Gemfile
    - node_modules/**/*
    - Rakefile

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - db/migrate/*
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
