AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'node_modules/**/*'
    - 'Rakefile'
    - 'spec/**/*'
    - 'Vagrantfile'

Style/FrozenStringLiteralComment:
  Enabled: false
